# Generated by Django 2.0.3 on 2018-05-26 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0002_auto_20180423_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='address_end_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='address_end_lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='address_start_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='address_start_lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='passengers_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
