# Generated by Django 2.0.3 on 2018-05-26 19:49

import blabla.blabla.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0003_auto_20180526_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='hour',
            field=blabla.blabla.fields.IntegerRangeField(default=12),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 26, 21, 49, 26, 713108)),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='passengers_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
