# Generated by Django 2.0.3 on 2018-05-27 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0004_auto_20180526_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 15, 53, 40, 994425)),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
