# Generated by Django 2.0.3 on 2018-05-31 13:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blabla', '0005_auto_20180527_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_start', django_google_maps.fields.AddressField(max_length=500)),
                ('address_end', django_google_maps.fields.AddressField(max_length=500)),
                ('address_start_lat', models.FloatField()),
                ('address_start_lng', models.FloatField()),
                ('address_end_lat', models.FloatField()),
                ('address_end_lng', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='passengers_signed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 31, 15, 9, 10, 711289)),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='hour',
            field=models.IntegerField(default=12),
        ),
    ]
