# Generated by Django 2.0.3 on 2018-06-03 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0006_auto_20180531_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 20, 15, 1, 69460)),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='passengers_signed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SearchModel',
        ),
    ]
