# Generated by Django 2.0.3 on 2018-06-03 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0008_auto_20180603_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 21, 35, 42, 118029)),
        ),
        migrations.RemoveField(
            model_name='searchmodel',
            name='route_id',
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='route_id',
            field=models.ManyToManyField(to='blabla.MapModel'),
        ),
    ]
